#include "constants.h"

const int BUILD_NUMBER = 454;
const int ENGINE_VERSION_MAJOR = 0;
const int ENGINE_VERSION_MINOR = 3;
const int ENGINE_VERSION_PATCH = 0;

const int IS_DEVELOPMENT_VERSION = 1;

const int GAME_VERSION_MAJOR = 0;
const int GAME_VERSION_MINOR = 1;
const int GAME_VERSION_PATCH = 0;
const char *GAME_NAME = "Apt 345";


const int MAX_TEXTURE_WIDTH = 4096;
const int MAX_TEXTURE_HEIGHT = 4096;

const float ROOM_TRANSITION_SPEED_HORIZONTAL = ((float)ROOM_WIDTH_PIXELS) / ((float)ROOM_TRANSITION_DURATION_MILLISECONDS);
const float ROOM_TRANSITION_SPEED_VERTICAL = ((float)ROOM_HEIGHT_PIXELS) / ((float)ROOM_TRANSITION_DURATION_MILLISECONDS);
